credentials:
  usernames:
    annalug:
      email: jsmith@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Anna Luiza
      password: annalu301293 # Will be hashed automatically
    paulo_oliveira:
      email: rbriggs@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Paulo Oliveira
      password: paulodho123 # Will be hashed automatically
cookie:
  expiry_days: 0
  key: "211521515" # Must be string
  name: "akakaka"
pre-authorized:
  emails:
  - melsby@gmail.com